import Modal from '@/ui/modal'
import Nav from './(components)/nav'
import './globals.css'
import LayoutClient from './layoutClient'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        {/* nav bar */}
        <Nav />
        {children}

        {/* client components that need to live at the root */}
        <LayoutClient />

      </body>
    </html>
  )
}
